name: RISC-V Ubuntu 22.04 Booting
on: [push]

jobs:
  riscv-booting-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joennlae/qemu-riscv-vec:latest
      env:
        CC: gcc-13
        CXX: g++-13
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Booted into RISC-V Ubuntu 22.04
        run: |
          echo "Hello world!"
          bash /root/ubuntu-riscv-vector/startup.sh
          echo "Booted into RISC-V Ubuntu 22.04"
          /root/ubuntu-riscv-vector/ssh_cmd.sh "gcc-13 -v"
